# --- SERENITY CONFIGURATION ---
serenity.project.name=USSD Dialer E2E
serenity.take.screenshots=AFTER_EACH_STEP
serenity.logging=VERBOSE
webdriver.timeouts.implicitlywait=10000
serenity.restart.browser.for.each=never

#       Ejecucion minimizada
headless.mode=false
chrome.switches=--window-size=1920,1080;--disable-gpu;--no-sandbox;--disable-dev-shm-usage;--window-position=-2000,0

# --- WebDriver Chrome Configuration ---
webdriver.driver=chrome
serenity.browser.maximized=false

# Ruta de chromedriver local
webdriver.chrome.driver=C:/WebDrivers/chromedriver/chromedriver.exe

# ============================================================
#  FEATURES
# ============================================================
feature.file.language = es
feature.file.encoding = utf8